"""initial schema

Revision ID: d3595f67e366
Revises: 
Create Date: 2026-03-27 20:42:44.328123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3595f67e366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planting_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variety', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_type', sa.Enum('seed', 'bulb', 'tuber', 'seedling', 'cutting', 'rhizome', 'bareroot', name='materialtype'), nullable=False),
    sa.Column('source_type', sa.Enum('bought', 'saved', 'gift', 'swap', name='sourcetype'), nullable=False),
    sa.Column('source_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planting_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planting_materials_name'), ['name'], unique=False)

    op.create_table('plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('started_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_method', sa.Enum('direct', 'indoor_start', 'pot', name='startmethod'), nullable=False),
    sa.Column('sown_depth_cm', sa.Float(), nullable=True),
    sa.Column('transplanted_at', sa.Date(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('end_reason', sa.Enum('frost', 'pulled', 'died', 'bolted', 'overwintered', 'complete', name='endreason'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['planting_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('germinated', 'first_true_leaves', 'established', 'first_flower', 'pollinated', 'first_fruit_set', 'pest', 'disease', 'pruned', 'thinned', 'custom', name='eventtype'), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_id', sa.Integer(), nullable=False),
    sa.Column('harvested_at', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'g', 'count', 'bunch', name='yieldunit'), nullable=False),
    sa.Column('quality', sa.Enum('poor', 'good', 'excellent', name='quality'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['planting_id'], ['plantings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvests')
    op.drop_table('events')
    op.drop_table('plantings')
    with op.batch_alter_table('planting_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_materials_name'))

    op.drop_table('planting_materials')
    # ### end Alembic commands ###
